"""API layer: executable contract (Pydantic DTOs) + FastAPI app."""

from muhideen.api.app import (
    ActiveToggleDTO,
    AppDeps,
    DisplayGroupUpdateDTO,
    DisplayRegisterDTO,
    DisplayUpdateDTO,
    PlaylistCreateDTO,
    PlaylistDTO,
    PlaylistImageUploadDTO,
    PlaylistItemDTO,
    create_app,
    create_production_app,
)
from muhideen.api.dto import (
    AuthRequestDTO,
    AuthResponseDTO,
    ConfigUpdateEventDTO,
    HeartbeatRequestDTO,
    HeartbeatResponseDTO,
    IqamahRuleDTO,
    NextEventDTO,
    PrayerDayDTO,
    SessionStatusDTO,
    SettingsDTO,
    StateEventDTO,
    TickEventDTO,
    VersionDTO,
)

__all__ = [
    "ActiveToggleDTO",
    "AppDeps",
    "AuthRequestDTO",
    "AuthResponseDTO",
    "ConfigUpdateEventDTO",
    "DisplayGroupUpdateDTO",
    "DisplayRegisterDTO",
    "DisplayUpdateDTO",
    "HeartbeatRequestDTO",
    "HeartbeatResponseDTO",
    "IqamahRuleDTO",
    "NextEventDTO",
    "PlaylistCreateDTO",
    "PlaylistDTO",
    "PlaylistImageUploadDTO",
    "PlaylistItemDTO",
    "PrayerDayDTO",
    "SessionStatusDTO",
    "SettingsDTO",
    "StateEventDTO",
    "TickEventDTO",
    "VersionDTO",
    "create_app",
    "create_production_app",
]
